version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-container
    ports:
      - "8080:8080"
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=changeme
      - xpack.security.enabled=false
    volumes:
      - ./.docker/elasticdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - app-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.0
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    depends_on:
      - elasticsearch
    networks:
      - app-network
  apm-server:
    image: docker.elastic.co/apm/apm-server:8.17.0
    container_name: apm-server
    user: root
    entrypoint: /bin/sh -c "chmod go-w /usr/share/apm-server/apm-server.yml && /usr/share/apm-server/apm-server -e"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - OUTPUT_ELASTICSEARCH_PASSWORD=changeme
    ports:
      - "8200:8200"
    depends_on:
      - elasticsearch
    networks:
      - app-network
    command: [ "sh", "-c", "chmod go-w /usr/share/apm-server/apm-server.yml && /usr/share/apm-server/apm-server -e" ]
    volumes:
      - ./apm/apm-server.yml:/usr/share/apm-server/apm-server.yml

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.13.0
    entrypoint: /bin/sh -c "chmod go-w /usr/share/filebeat/filebeat.yml && /usr/share/filebeat/filebeat -e"
    container_name: filebeat
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./beats/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
    restart: on-failure
    depends_on:
      - elasticsearch
    networks:
      - app-network
    command: [ "sh", "-c", "chmod go-w /usr/share/filebeat/filebeat.yml && /usr/share/filebeat/filebeat -e" ]
networks:
  app-network:
    driver: bridge
