# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

# Alertmanager configuration
# Uncomment and configure if you need alerting.
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus:9090']  # Usando o nome do serviço Prometheus no Docker Compose
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'cadvisor:8080'  # Usando o nome do serviço cadvisor no Docker Compose
  - job_name: 'app'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'app:8081'  # Usando o nome do serviço da aplicação no Docker Compose
