apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-natan-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-natan
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 25
