output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "elastic"
  password: "elasticpassword"

setup.kibana:
  host: "http://kibana:5601"

heartbeat.monitors:
  - type: http
    urls: ["http://localhost:9200"]
    schedule: "@every 10s"
